title: Vikas Pawar
logo: /assets/ProfilePicH.png
#show_downloads: true 
#description: User Experience Designer
github:
  zip_url: http://example.com/download.zip
  another_url: another value
theme: jekyll-theme-minimal
